baseURL = "https://ethereal-26857.github.io/LearningNotes/"
languageCode = "zh-cn"
title = "Anne 的学习笔记"
theme = "stack"

[pagination]
pagerSize = 5

[params]
mainSections = ["posts"]
featuredImageField = "image"
rssFullContent = true
favicon = "/favicon.ico"

[params.sidebar]
subtitle = "专业课 | 科研 | 杂七杂八的涉猎 | 机器人"

[params.sidebar.avatar]
enabled = true
local = true
src = "img/avatar.jpg"

[params.article]
headingAnchor = true
math = true
readingTime = true

[params.footer]
since = 2024

[params.dateFormat]
published = "2006-01-02"

[params.widgets]
homepage = [
  { type = "search" },
  { type = "archives" },
  { type = "tag-cloud" }
]

page = [
  { type = "toc" }
]

[menu]

  [[menu.main]]
  name = "首页"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "文章"
  url = "/posts/"
  weight = 2

  [[menu.main]]
  name = "GitHub"
  url = "https://github.com/Ethereal-26857"
  weight = 3
